// <auto-generated />
using CitiesManager.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace CitiesManager.WebAPI.Migrations
{
    [DbContext(typeof(MsSqlDbContext))]
    partial class MsSqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitiesManager.WebAPI.Entities.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cityId");

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("cityCode");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("cityName");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,15)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,15)")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("RegAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 9, 27, 7, 41, 38, 355, DateTimeKind.Local).AddTicks(6228))
                        .HasColumnName("regAt");

                    b.HasKey("CityId");

                    b.ToTable("tblCities", "CitiesManagerDb");

                    b.HasData(
                        new
                        {
                            CityId = new Guid("a32054f2-54c9-4a95-91e6-1b24558573a6"),
                            CityCode = "MGQ",
                            CityName = "Mogadishu",
                            Latitude = 2.05368398776368m,
                            Longitude = 45.31820111676328m,
                            RegAt = new DateTime(2023, 9, 27, 7, 41, 38, 355, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
